languageCode: de-ch
title: Adesso Olten
theme: wl-theme
relativeURLs: true
params:
  logo: adesso_logo.svg
  favicon: adesso_favicon.png
imaging:
  quality: 90
  resampleFilter: Lanczos
  hint: picture
  anchor: Top